# version: '3.3'
name: foodgram

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ../.env

  backend:
    image: foodgram-backend
    container_name: foodgram-backend
    env_file: ../.env
    command: ../backend/start_backend.sh
    volumes:
      - static:/backend_static
      - media:/media
      - ../data:/app/data:ro
    depends_on:
      - db
  frontend:
    image: foodgram-frontend
    container_name: foodgram-frontend
    # build: ../frontend
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles
  nginx:
    image: foodgram-proxy
    container_name: foodgram-proxy
    build: ../nginx
    ports:
      - "80:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api-docs:ro
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
      - frontend
